\begin{align*}
    SVM(x;W,b) = sign(w^Tx+b)\\
    SVM(x;\alpha,b) = sign(\sum_{i=1}^Nt^{(i)}\alpha_ix^Tx^{(i)}+b)
\end{align*}


<h4> If they give you the alphas and not the weights</h4>

In [44]:
import numpy as np

Trainingset = np.array([[0,0,2],[0,1,8],[1,0,6],[1,1,7],[1,1,3],])                 #write here training data
targets = np.array([1,1,-1,-1,1])                                                  #write here target values
alphacoefficients = np.array([0,1,0.5,1,0.5])                                      #write here alpha
bias=0                                                                             #write here bias

print('How many support vectors are required?')

result = np.where(alphacoefficients > 0)
print("There are", len(result[0]), 'support vectors. All that have alpha > 0\nThese corresponde to the x values:')

for i in result:
    print(Trainingset[i])

How many support vectors are required?
There are 4 support vectors. All that have alpha > 0
These corresponde to the x values:
[[0 1 8]
 [1 0 6]
 [1 1 7]
 [1 1 3]]


In [56]:
print('Using a linear kernel and b=-3, how does this SVM classify x=(1,1,8)^T ?')
bias = -3                                                                              #change here bias
Testset = np.array([1,1,8])                                                            #write here test sample
print('o(x)=sgn(\sum_{i=1}^',len(result[0]),' t^(i) . alpha_i . x^T . x^(i) + b)\n')

print('o(x)=sgn(', end="")

for i in range(np.min(result),np.max(result)+1):
    print(targets[i],'.',alphacoefficients[i],'.',Testset,'',Trainingset[i],'^T + ')
print(bias,')')

print('\no(x)=sgn(', end="")
for i in range(np.min(result),np.max(result)+1):
    print(targets[i]*alphacoefficients[i]*Testset.dot(Trainingset[i].reshape(-1,1)),'+',end="")
print(bias,')')

print('\t=sgn(', end="")
sum=bias
for i in range(np.min(result),np.max(result)+1):
    sum+=targets[i]*alphacoefficients[i]*Testset.dot(Trainingset[i].reshape(-1,1))
print(sum,')')

print('\t=',np.sign(sum))

Using a linear kernel and b=-3, how does this SVM classify x=(1,1,8)^T ?
o(x)=sgn(\sum_{i=1}^ 4  t^(i) . alpha_i . x^T . x^(i) + b)

o(x)=sgn(1 . 1.0 . [1 1 8]  [0 1 8] ^T + 
-1 . 0.5 . [1 1 8]  [1 0 6] ^T + 
-1 . 1.0 . [1 1 8]  [1 1 7] ^T + 
1 . 0.5 . [1 1 8]  [1 1 3] ^T + 
-3 )

o(x)=sgn([65.] +[-24.5] +[-58.] +[13.] +-3 )
	=sgn([-7.5] )
	= [-1.]


In [95]:
Trainingset = np.array([[3.29,1.60],[2.29,1.81],
                        [2.07,0.91],[1.84,1.37],
                        [3.06,1.66] ,[1.41,0.51],
                        [0.70,1.25] ,[0.22,0.35],                              #OR DELETE
                        [1.18,0.25] ,[0.83,0.62]])                               #write here training data
targets = np.array([1,1,1,1,1,-1,-1,-1,-1,-1])                                   #write here target values
alphacoefficients = np.array([0,0,3.36,0,0,3.36,0,0,0,0])                        #write here alpha

supportvectors = np.where(alphacoefficients > 0)



print('What is the weight vector?')
print('W=\sum_{i=1}^',len(result[0]),' t^(i) . alpha_i . x^(i)')
print('W=',end="")
w=[0]*(Trainingset.shape[1])
for i in range(np.min(supportvectors),np.max(supportvectors)+1):
    print(targets[i]*alphacoefficients[i]*Trainingset[i],'+',end="")
    w= np.add(w,targets[i]*alphacoefficients[i]*Trainingset[i])
print('\nw =',w)

What is the weight vector?
W=\sum_{i=1}^ 4  t^(i) . alpha_i . x^(i)
W=[6.9552 3.0576] +[0. 0.] +[0. 0.] +[-4.7376 -1.7136] +
w = [2.2176 1.344 ]


In [101]:
print('What is the boundary equation?')
print('We need the weight vector from before and the bias.')
print('We can use a support vector to find the bias first\n')
print(w,' . ', Trainingset[supportvectors[0][0]],'^T + b = ', targets[supportvectors[0][0]] )
print('\tb=',targets[supportvectors[0][0]],'-',w.dot(Trainingset[supportvectors[0][0]].reshape(-1,1)))
b = targets[supportvectors[0][0]] - w.dot(Trainingset[supportvectors[0][0]].reshape(-1,1))
print('\tb=',b,'\n')
print('Therefore the boundary equation is:')
print('\t w^T . x + b = 0')
print('\t',np.round(w[0],3),'x1 + ',np.round(w[1],3),'x2 + ',np.round(b,3),' = 0')

What is the boundary equation?
When the output is exactly the same as the target value
	 w^T . x^(i) + b = t^(i)
We can use a support vector to find the bias first

[2.2176 1.344 ]  .  [2.07 0.91] ^T + b =  1
	b= 1 - [5.813472]
	b= [-4.813472] 

Therefore the boundary equation is:
	 w^T . x + b = 0
	 2.218 x1 +  1.344 x2 +  [-4.813]  = 0


<h4>No alpha coefficients but give weights and bias</h4>

In [145]:
Trainingset = np.array([[0.68,1.26],[-0.25,-0.51],
                        [0.83,-0.32],[1.44,1.04],
                        [1.14,3.21] ,[-2.19,5.1],
                        [-2.47,3.76] ,[-1.19,6.39],                              #OR DELETE
                        [-2.3,3.48] ,[-0.94,5.04]])                              #write here training data
targets = np.array([1,1,1,1,1,-1,-1,-1,-1,-1])                                   #write here target values
weights= np.array([0.544,-0.474])
bias=1.902
print('What are the support vectors?')
print('\nWhen the output is exactly the same as the target value')
print('\t w^T . x^(i) + b = t^(i)\n')

sp=[]
supportvectors=[]

for i in range(0,len(Trainingset)):
    o = np.round(weights.dot(Trainingset[i].reshape(-1,1)) + bias,2)
    print('For x(',i,'):',weights,'.',Trainingset[i],'+',bias,'=',o,' ',o==targets[i],' ',targets[i])
    if o == targets[i]:
        sp.append(i+1)
        supportvectors.append(Trainingset[i])
        print()
    o=0
    
sp = np.array(sp)
supportvectors = np.array(supportvectors)
print('\nThe support vectors are: ', sp,'\nMore specifically:\n',supportvectors)
    

What are the support vectors?

When the output is exactly the same as the target value
	 w^T . x^(i) + b = t^(i)

For x( 0 ): [ 0.544 -0.474] . [0.68 1.26] + 1.902 = [1.67]   [False]   1
For x( 1 ): [ 0.544 -0.474] . [-0.25 -0.51] + 1.902 = [2.01]   [False]   1
For x( 2 ): [ 0.544 -0.474] . [ 0.83 -0.32] + 1.902 = [2.51]   [False]   1
For x( 3 ): [ 0.544 -0.474] . [1.44 1.04] + 1.902 = [2.19]   [False]   1
For x( 4 ): [ 0.544 -0.474] . [1.14 3.21] + 1.902 = [1.]   [ True]   1

For x( 5 ): [ 0.544 -0.474] . [-2.19  5.1 ] + 1.902 = [-1.71]   [False]   -1
For x( 6 ): [ 0.544 -0.474] . [-2.47  3.76] + 1.902 = [-1.22]   [False]   -1
For x( 7 ): [ 0.544 -0.474] . [-1.19  6.39] + 1.902 = [-1.77]   [False]   -1
For x( 8 ): [ 0.544 -0.474] . [-2.3   3.48] + 1.902 = [-1.]   [ True]   -1

For x( 9 ): [ 0.544 -0.474] . [-0.94  5.04] + 1.902 = [-1.]   [ True]   -1


The support vectors are:  [ 5  9 10] 
More specifically:
 [[ 1.14  3.21]
 [-2.3   3.48]
 [-0.94  5.04]]


In [167]:
print('What are the dual coefficients alpha?')
print('Only those that are support vectors have a positive alpha ')

for i in range(0,len(supportvectors)):
    print('t^(',sp[i],') alpha',sp[i],'x^(',sp[i],')^T x^(',sp[i],') + ',end="")
    for k in range(0,len(supportvectors)):
        if k != i:
            print('t^(',sp[k],') alpha',sp[k],'x^(',sp[k],')^T x^(',sp[i],') + ',end="")
    print('= t^(',sp[i],')')

print('\n\n')

    
for i in range(0,len(supportvectors)):
    indexi = sp[i]-1
    a=targets[indexi]*Trainingset[indexi].dot(Trainingset[indexi].reshape(-1,1))
    print(a,'alpha',sp[i],' + ',end="")
    for k in range(0,len(supportvectors)):
        if k != i:
            indexk = sp[k]-1
            a=targets[indexk]*Trainingset[indexk].dot(Trainingset[indexi].reshape(-1,1))
            print(a,'alpha',sp[k],' + ',end="")
    print( '= ', np.round(targets[indexi]-bias,3))
    a=0

What are the dual coefficients alpha?
Only those that are support vectors have a positive alpha 
t^( 5 ) alpha 5 x^( 5 )^T x^( 5 ) + t^( 9 ) alpha 9 x^( 9 )^T x^( 5 ) + t^( 10 ) alpha 10 x^( 10 )^T x^( 5 ) + = t^( 5 )
t^( 9 ) alpha 9 x^( 9 )^T x^( 9 ) + t^( 5 ) alpha 5 x^( 5 )^T x^( 9 ) + t^( 10 ) alpha 10 x^( 10 )^T x^( 9 ) + = t^( 9 )
t^( 10 ) alpha 10 x^( 10 )^T x^( 10 ) + t^( 5 ) alpha 5 x^( 5 )^T x^( 10 ) + t^( 9 ) alpha 9 x^( 9 )^T x^( 10 ) + = t^( 10 )



[11.6037] alpha 5  + [-8.5488] alpha 9  + [-15.1068] alpha 10  + =  -0.902
[-17.4004] alpha 9  + [8.5488] alpha 5  + [-19.7012] alpha 10  + =  -2.902
[-26.2852] alpha 10  + [15.1068] alpha 5  + [-19.7012] alpha 9  + =  -2.902


In [142]:
print('What is the value margin?')
print('margin = 1 / ||w||2')
print('\t= 1 / \sqrt{',weights[0],'^2 ',weights[1],'^2 } ')
print('\t=',np.round(1/np.linalg.norm(weights),3))

What is the value margin?
margin = 1 / ||w||2
	= 1 / \sqrt{ 0.544 ^2 -0.474 ^2 } 
	= 1.386
